# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Update and deploy

on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: denolib/setup-deno@master
      - uses: arduino/setup-protoc@master
      - run: npm install google-protobuf@latest
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - id: check-version
        run: deno run --allow-read --allow-run tools/check-version.ts
      - if: ${{ steps.check-version.outputs.version }}
        run: npm test
      # Now build with github url + @version
      - if: ${{ steps.check-version.outputs.version }}
        run: npm run build -- ${{ steps.check-version.outputs.version }}
      - if: ${{ steps.check-version.outputs.version }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          commit_message: ${{ steps.check-version.outputs.version }}
          commit_user_name: Release Bot @GitHub Actions
          commit_author: Release Bot <actions@github.com>
          tagging_message: ${{ steps.check-version.outputs.version }}
          push_options: '--force'
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
